"""Edge-case tests for lockfile parsing, the threat feed, persistence
hunting and the credential audit.

These tests focus on the *weird* inputs and failure modes: malformed
caches, binary lockfiles, missing subprocesses, platform switches and
secret redaction. Every check under test promises "never raises, degrades
gracefully" — these tests hold it to that promise.

No real data files are ever modified; the feed cache is redirected into
tmp_path per test via NPM_SHIELD_FEED_CACHE.
"""
import json
import subprocess
import sys
from pathlib import Path

import pytest

from npm_shield import lockfile
from npm_shield.audit import CredentialAudit
from npm_shield.feed import ThreatFeed, _looks_like_package
from npm_shield.persistence import PersistenceHunter

# Synthetic credential value — never a real secret.
FAKE_TOKEN = "npm_EDGE_FAKE_TOKEN_7d2b1e"

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _write(tmp_path, name, content):
    p = tmp_path / name
    p.write_text(content)
    return p


def _make_feed(tmp_path, monkeypatch):
    """A ThreatFeed pointed at a hermetic tmp cache dir."""
    monkeypatch.setenv("NPM_SHIELD_FEED_CACHE", str(tmp_path / "feed-cache"))
    return ThreatFeed(offline_mode=True)


# ---------------------------------------------------------------------------
# LOCKFILE edge cases
# ---------------------------------------------------------------------------


def test_npm_lock_v2(tmp_path):
    """lockfileVersion 2 uses the flat ``packages`` map and parses cleanly."""
    p = _write(
        tmp_path,
        "package-lock.json",
        json.dumps(
            {
                "name": "app",
                "version": "1.0.0",
                "lockfileVersion": 2,
                "packages": {
                    "": {"name": "app", "dependencies": {"keyv": "^6.0.0"}},
                    "node_modules/keyv": {"version": "6.0.0"},
                    "node_modules/lodash": {"version": "4.17.21"},
                },
            }
        ),
    )
    out = lockfile.parse_lockfile(p)
    assert out["keyv"] == "6.0.0"
    assert out["lodash"] == "4.17.21"


def test_npm_lock_v1_scoped(tmp_path):
    """v1 nested-deps trees keep '@scope/name' package names intact."""
    p = _write(
        tmp_path,
        "package-lock.json",
        json.dumps(
            {
                "name": "app",
                "lockfileVersion": 1,
                "dependencies": {
                    "@babel/core": {
                        "version": "7.24.0",
                        "requires": {"@babel/parser": "^7.24.0"},
                    },
                    "@scope/pkg": {"version": "2.0.1"},
                },
            }
        ),
    )
    out = lockfile.parse_lockfile(p)
    assert out["@babel/core"] == "7.24.0"
    assert out["@scope/pkg"] == "2.0.1"


def test_v3_nested_scoped(tmp_path):
    """Flat packages key 'node_modules/@scope/pkg' maps to name '@scope/pkg'."""
    p = _write(
        tmp_path,
        "package-lock.json",
        json.dumps(
            {
                "lockfileVersion": 3,
                "packages": {
                    "": {"name": "app"},
                    "node_modules/@scope/pkg": {"version": "3.1.4"},
                    "node_modules/@scope/other": {"version": "1.2.3"},
                },
            }
        ),
    )
    out = lockfile.parse_package_lock_v3(p)
    assert out["@scope/pkg"] == "3.1.4"
    assert out["@scope/other"] == "1.2.3"


def test_yarn_berry_returns_empty(tmp_path):
    """Yarn berry lockfiles (__metadata:) are out of scope -> {}."""
    berry = (
        '# This file is generated by running "yarn install" inside your project.\n'
        "__metadata:\n"
        "  version: 8\n"
        "  cacheKey: 10c0\n"
        "\n"
        '"keyv@npm:^6.0.0":\n'
        "  version: 6.0.0\n"
        "  resolution: \"keyv@npm:6.0.0\"\n"
    )
    p = _write(tmp_path, "yarn.lock", berry)
    assert lockfile.parse_yarn_lock(p) == {}
    assert lockfile.parse_lockfile(p) == {}


def test_pnpm_fallback_no_yaml(tmp_path, monkeypatch):
    """With PyYAML unavailable the line-based fallback still returns a dict."""
    p = _write(
        tmp_path,
        "pnpm-lock.yaml",
        "lockfileVersion: '6.0'\n"
        "\n"
        "dependencies:\n"
        "  keyv:\n"
        "    specifier: ^6.0.0\n"
        "    version: 6.0.0\n"
        "\n"
        "packages:\n"
        "  /keyv@6.0.0:\n"
        "    resolution: {integrity: sha512-abc123}\n"
        "    engines: {node: '>=12'}\n",
    )
    monkeypatch.setattr(lockfile, "_import_yaml", lambda: None)
    out = lockfile.parse_pnpm_lock(p)
    assert isinstance(out, dict)
    assert out.get("keyv") == "6.0.0"


def test_yarn_quoted_specs(tmp_path):
    """Quoted yarn v1 headers (\"keyv@^6.0.0\":) parse to name -> version."""
    quoted = (
        "# yarn lockfile v1\n"
        '"keyv@^6.0.0":\n'
        '  version "6.0.0"\n'
        '  resolved "https://registry.yarnpkg.com/keyv/-/keyv-6.0.0.tgz"\n'
        "\n"
        '"@babel/core@^7.0.0", "@babel/core@^7.24.0":\n'
        '  version "7.24.0"\n'
    )
    p = _write(tmp_path, "yarn.lock", quoted)
    out = lockfile.parse_yarn_lock(p)
    assert out.get("keyv") == "6.0.0"
    assert out.get("@babel/core") == "7.24.0"


def test_lockfile_binary_file(tmp_path):
    """A lockfile full of null bytes yields {} instead of crashing."""
    p = tmp_path / "package-lock.json"
    p.write_bytes(b"\x00\x01\x02\x03\xff not a lockfile \x00\x00")
    assert lockfile.parse_lockfile(p) == {}
    assert lockfile.parse_package_lock_v3(p) == {}


def test_detect_lockfile_content_sniff(tmp_path):
    """Oddly-named files are detected by content (pnpm via lockfileVersion:)."""
    p = _write(
        tmp_path,
        "weird.txt",
        "lockfileVersion: '6.0'\n"
        "packages:\n"
        "  /keyv@6.0.0:\n"
        "    resolution: {integrity: sha512-x}\n",
    )
    assert lockfile.detect_lockfile_type(p) == "pnpm"
    assert isinstance(lockfile.parse_lockfile(p), dict)


# ---------------------------------------------------------------------------
# FEED edge cases
# ---------------------------------------------------------------------------


def test_corrupt_cache_file(tmp_path, monkeypatch):
    """Garbage in the cache file: local data survives, no crash, no timestamp."""
    feed = _make_feed(tmp_path, monkeypatch)
    feed.cache_file.write_text("{ definitely not json")
    pkgs = feed.get_affected_packages()
    assert "keyv" in pkgs  # local verified data still present
    assert pkgs["keyv"] == ["6.0.0"]
    assert feed.last_updated is None


def test_cache_file_valid(tmp_path, monkeypatch):
    """A valid cache merges extra packages with the local verified data."""
    feed = _make_feed(tmp_path, monkeypatch)
    feed.cache_file.write_text(
        json.dumps(
            {
                "fetched_at": 1700000000,
                "sources": ["https://example.invalid/advisory"],
                "packages": {"extra-pkg": ["1.0.0"], "keyv": ["9.9.9"]},
            }
        )
    )
    pkgs = feed.get_affected_packages()
    assert pkgs["extra-pkg"] == ["1.0.0"]
    assert pkgs["keyv"] == ["6.0.0", "9.9.9"]  # local + cached union
    assert feed.last_updated == 1700000000


def test_version_matches_edge():
    """Wildcard, empty-string version and empty version lists are handled."""
    assert ThreatFeed.version_matches(None, ["*"]) is True
    assert ThreatFeed.version_matches("", ["6.0.0"]) is False
    assert ThreatFeed.version_matches("6.0.0", []) is False


def test_looks_like_package_helper():
    """The HTML-noise filter rejects obvious non-package matches."""
    assert _looks_like_package("node") is False  # in _SKIP_NAMES
    assert _looks_like_package("lodash") is False  # popular benign package
    assert _looks_like_package("a") is False  # too short
    assert _looks_like_package("http") is False  # in _SKIP_NAMES


def test_fetch_failure_graceful(tmp_path, monkeypatch):
    """Every feed source failing -> update() returns False, never raises."""

    def raiser(url, timeout=12):
        raise OSError("network unreachable")

    # Isolate the feed cache: without this, a cache written by a previous
    # run/feed-update lives in the real user cache dir and last_updated
    # reads a stale timestamp, making the assertion flaky across machines.
    monkeypatch.setenv("NPM_SHIELD_FEED_CACHE", str(tmp_path / "feed_cache"))
    monkeypatch.setattr(ThreatFeed, "_fetch", raiser)
    feed = ThreatFeed(offline_mode=False)  # network path, but _fetch is broken
    assert feed.update() is False
    assert feed.last_updated is None
    assert not feed.cache_file.exists()


# ---------------------------------------------------------------------------
# PERSISTENCE edge cases
# ---------------------------------------------------------------------------


def test_platform_windows_skips_linux_paths(monkeypatch, tmp_path):
    """On win32 the linux ~/.config artifact must not be flagged."""
    home = tmp_path / "home"
    state = home / ".config" / "gh-token-monitor"
    state.mkdir(parents=True)
    (state / "state.json").write_text('{"watcher": "active"}')

    # sanity: the real (linux) platform DOES flag the artifact
    linux_hunter = PersistenceHunter(home=str(home))
    assert linux_hunter.check_home()

    # simulate Windows by swapping the instance platform attr
    win_hunter = PersistenceHunter(home=str(home))
    monkeypatch.setattr(win_hunter, "platform", "win32")
    assert win_hunter.check_home() == []


def test_check_temp_dirs_clean(monkeypatch, tmp_path):
    """No bun-dl-* dirs anywhere -> no findings."""
    clean = tmp_path / "clean-tmp"
    clean.mkdir()
    monkeypatch.setenv("TMPDIR", str(clean))
    monkeypatch.setenv("TEMP", str(tmp_path / "no-such-temp"))
    monkeypatch.setenv("TMP", str(tmp_path / "no-such-tmp"))
    findings = PersistenceHunter(home=str(tmp_path)).check_temp_dirs()
    assert findings == []


def test_check_temp_dirs_found(monkeypatch, tmp_path):
    """A bun-dl-* dir under $TMPDIR is reported as a loader artifact."""
    parent = tmp_path / "tmp"
    parent.mkdir()
    (parent / "bun-dl-xyz").mkdir()
    monkeypatch.setenv("TMPDIR", str(parent))
    monkeypatch.setenv("TEMP", str(tmp_path / "no-such-temp"))
    monkeypatch.setenv("TMP", str(tmp_path / "no-such-tmp"))
    findings = PersistenceHunter(home=str(tmp_path)).check_temp_dirs()
    assert findings
    assert any("bun-dl" in (f.message or "") for f in findings)
    assert all(f.severity == "medium" for f in findings)


def test_systemd_services_error(monkeypatch, tmp_path):
    """systemctl failing must not crash the systemd unit check."""

    def raiser(*args, **kwargs):
        raise OSError("systemctl unavailable")

    monkeypatch.setattr("npm_shield.persistence.subprocess.run", raiser)
    hunter = PersistenceHunter(home=str(tmp_path))
    monkeypatch.setattr(hunter, "platform", "linux")
    assert hunter._check_systemd_services() == []


def test_check_processes_subprocess_fallback(monkeypatch, tmp_path):
    """psutil unavailable -> 'ps aux' fallback still catches gh-token-monitor."""
    monkeypatch.setitem(sys.modules, "psutil", None)

    def fake_run(*args, **kwargs):
        return subprocess.CompletedProcess(
            args=args[0] if args else [],
            returncode=0,
            stdout=(
                "USER PID %CPU %MEM VSZ RSS TTY STAT START TIME COMMAND\n"
                "alice 1234 0.0 0.1 12345 6789 ? S 12:00 0:01 "
                "node /home/alice/.config/gh-token-monitor/monitor.js\n"
            ),
        )

    monkeypatch.setattr("npm_shield.persistence.subprocess.run", fake_run)
    findings = PersistenceHunter(home=str(tmp_path)).check_processes()
    assert findings
    assert any(
        f.severity == "critical" and "gh-token-monitor" in (f.message or "")
        for f in findings
    )


# ---------------------------------------------------------------------------
# AUDIT edge cases
# ---------------------------------------------------------------------------


def test_npmrc_env_override(monkeypatch, tmp_path):
    """NPM_CONFIG_USERCONFIG redirects the npmrc check to a custom file."""
    custom = tmp_path / "custom-npmrc"
    custom.write_text(f"//registry.npmjs.org/:_authToken={FAKE_TOKEN}\n")
    monkeypatch.setenv("NPM_CONFIG_USERCONFIG", str(custom))
    finding = CredentialAudit(home=str(tmp_path / "unused-home")).check_npmrc()
    assert finding is not None
    assert finding.severity == "high"
    assert finding.file_path == str(custom)
    assert FAKE_TOKEN not in str(finding.to_dict())  # value stays redacted


def test_git_credentials_medium(tmp_path):
    """A plaintext .git-credentials file is a medium-severity finding."""
    home = tmp_path / "home"
    home.mkdir()
    (home / ".git-credentials").write_text(
        "https://0.0.0.0:0/test\n"
    )
    finding = CredentialAudit(home=str(home)).check_gh_creds()
    assert finding is not None
    assert finding.severity == "medium"
    assert finding.category == "gh_creds"


def test_ignore_scripts_subprocess_error(monkeypatch, tmp_path):
    """npm unavailable -> info finding about the unknown setting, no crash."""

    def raiser(*args, **kwargs):
        raise OSError("npm not installed")

    monkeypatch.setattr("npm_shield.audit.subprocess.run", raiser)
    finding = CredentialAudit(home=str(tmp_path)).check_ignore_scripts()
    assert finding is not None
    assert finding.severity == "info"
    assert finding.category == "ignore_scripts"


def test_env_secrets_redacted(monkeypatch, tmp_path):
    """Env secrets are reported by NAME only — values never leak."""
    monkeypatch.setenv("NPM_TOKEN", "super_secret_value_xyz")
    finding = CredentialAudit(home=str(tmp_path)).check_env_secrets()
    assert finding is not None
    assert finding.severity == "high"
    assert "NPM_TOKEN" in (finding.message or "")
    dumped = str(finding.to_dict())
    assert "super_secret_value_xyz" not in dumped


# --- Regression tests for red-team / cross-verification audit findings ---

def test_npm_alias_in_package_lockfile(tmp_path):
    """npm alias entries (version: 'npm:keyv@6.0.0') resolve to the
    real package name for poisoning checks."""
    from npm_shield.lockfile import parse_package_lock
    lf = tmp_path / "package-lock.json"
    lf.write_text(json.dumps({
        "lockfileVersion": 3,
        "packages": {
            "node_modules/my-keyv": {"version": "npm:keyv@6.0.0"},
            "node_modules/real-pkg": {"version": "1.0.0"},
        },
    }))
    pkgs = parse_package_lock(str(lf))
    # alias should resolve to keyv@6.0.0, not my-keyv@npm:keyv@6.0.0
    assert pkgs.get("keyv") == "6.0.0", f"alias not resolved: {pkgs}"
    assert pkgs.get("my-keyv") is None


def test_npm_alias_with_caret(tmp_path):
    """npm alias with version range: npm:^6.0.0 -> keyv version ^6.0.0"""
    from npm_shield.lockfile import parse_package_lock
    lf = tmp_path / "package-lock.json"
    lf.write_text(json.dumps({
        "lockfileVersion": 3,
        "packages": {
            "node_modules/alias": {"version": "npm:keyv@^6.0.0"},
        },
    }))
    pkgs = parse_package_lock(str(lf))
    assert pkgs.get("keyv") == "^6.0.0"


def test_yarn_version_with_s_char():
    """Yarn spec versions containing 's' (e.g. '1.0.0-snapshot')
    parse correctly after the regex typo fix."""
    from npm_shield.lockfile import _NAME_VERSION_RE
    m = _NAME_VERSION_RE.match("keyv@1.0.0-snapshot")
    assert m is not None
    assert m.group(1) == "keyv"
    assert m.group(2) == "1.0.0-snapshot"


def test_pnpm_peer_dep_suffix_stripped():
    """pnpm v6/v9 keys with peer annotations: keyv@6.0.0(ts@5) -> 6.0.0"""
    from npm_shield.lockfile import _split_pnpm_key
    name, ver = _split_pnpm_key("/keyv@6.0.0(typescript@5.5.0)")
    assert name == "keyv"
    assert ver == "6.0.0", f"peer suffix not stripped: {ver}"


def test_pnpm_v9_snapshots_section(tmp_path):
    """pnpm-lock.yaml v9 'snapshots:' section is parsed."""
    from npm_shield.lockfile import parse_pnpm_lock
    lf = tmp_path / "pnpm-lock.yaml"
    lf.write_text("""
lockfileVersion: '9.0'

snapshots:
  /keyv@6.0.0:
    dependencies: {}
  /flat-cache@6.1.24:
    dependencies: {}
""")
    pkgs = parse_pnpm_lock(str(lf))
    assert pkgs.get("keyv") == "6.0.0", f"snapshots section not parsed: {pkgs}"


def test_package_json_alias_dependency_resolved(tmp_path):
    """package.json with npm alias dependency is checked against affected list."""
    from npm_shield.engine import Scanner
    pj = tmp_path / "package.json"
    pj.write_text(json.dumps({
        "name": "my-app",
        "version": "1.0.0",
        "dependencies": {
            "my-keyv": "npm:keyv@6.0.0"
        },
    }))
    scanner = Scanner()
    findings = scanner._scan_package_json_file(pj)
    alias_hits = [f for f in findings if "alias" in (f.detail or "")]
    assert len(alias_hits) >= 1, "npm alias in package.json not detected"


# === Regression tests for audit-found issues ===

def test_npm_alias_standard_resolution(tmp_path):
    """npm:keyv@6.0.0 alias in lockfile resolves to keyv@6.0.0."""
    from npm_shield.lockfile import parse_package_lock
    lf = tmp_path / "package-lock.json"
    lf.write_text(json.dumps({
        "lockfileVersion": 3,
        "packages": {
            "node_modules/my-keyv": {"version": "npm:keyv@6.0.0"},
        },
    }))
    pkgs = parse_package_lock(str(lf))
    assert pkgs.get("keyv") == "6.0.0", f"alias not resolved: {pkgs}"
    assert pkgs.get("my-keyv") is None


def test_npm_alias_bare_package(tmp_path):
    """npm:keyv (no version) resolves to keyv with 'unknown' version."""
    from npm_shield.lockfile import parse_package_lock
    lf = tmp_path / "package-lock.json"
    lf.write_text(json.dumps({
        "lockfileVersion": 3,
        "packages": {
            "node_modules/bare": {"version": "npm:flat-cache"},
        },
    }))
    pkgs = parse_package_lock(str(lf))
    assert "flat-cache" in pkgs, f"bare alias not detected: {pkgs}"


def test_npm_alias_version_only_skipped():
    """npm:^6.0.0 (version-only, no package name) returns None."""
    from npm_shield.lockfile import _resolve_alias
    result = _resolve_alias("npm:^6.0.0")
    assert result is None, f"should return None for version-only alias: {result}"


def test_npm_alias_wildcard_skipped():
    """npm:* wildcards are skipped."""
    from npm_shield.lockfile import _resolve_alias
    assert _resolve_alias("npm:*") is None


def test_pnpm_peer_dep_stripped():
    """pnpm keyv@6.0.0(typescript@5.5.0) → keyv, 6.0.0"""
    from npm_shield.lockfile import _split_pnpm_key
    name, ver = _split_pnpm_key("/keyv@6.0.0(typescript@5.5.0)")
    assert name == "keyv" and ver == "6.0.0"


def test_fallback_regex_nested_objects():
    """Fallback regex handles nested objects before 'version' key."""
    from npm_shield.lockfile import _extract_lock_packages_fallback, _packages_to_out
    # Nested object before version field (old [^}]*? would stop at first })
    text = '"node_modules/keyv": {"integrity": "sha512-abc", "dependencies": {"sub": {"version": "1.0.0"}}, "version": "6.0.0"}'
    result = _extract_lock_packages_fallback(text)
    pkgs = _packages_to_out(result)
    assert pkgs.get("keyv") == "6.0.0", f"nested object broke regex: {pkgs}"


def test_package_json_alias_dependency_detected(tmp_path):
    """package.json with 'my-keyv': 'npm:keyv@6.0.0' is flagged."""
    from npm_shield.engine import Scanner
    pj = tmp_path / "package.json"
    pj.write_text(json.dumps({
        "name": "app",
        "version": "1.0.0",
        "dependencies": {"my-keyv": "npm:keyv@6.0.0"},
    }))
    s = Scanner()
    r = s.scan_project(str(tmp_path))
    alias_hits = [f for f in r.findings if f.category == "poisoned_package"]
    assert len(alias_hits) >= 1, "npm alias dependency not detected"
