"""Tests for npm_shield.lockfile parsing (v1/v3/yarn/pnpm + detection)."""
import json
from pathlib import Path

import pytest

from npm_shield import lockfile

YARN_V1 = """# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# yarn lockfile v1


keyv@^6.0.0:
  version "6.0.0"
  resolved "https://registry.yarnpkg.com/keyv/-/keyv-6.0.0.tgz"
  integrity sha512-abc
  dependencies:
    json-buffer "3.0.1"

lodash@^4.17.21:
  version "4.17.21"
  resolved "https://registry.yarnpkg.com/lodash/-/lodash-4.17.21.tgz"
  integrity sha512-def
"""

PNPM_YAML = """lockfileVersion: '6.0'

dependencies:
  keyv:
    specifier: ^6.0.0
    version: 6.0.0

packages:
  /keyv@6.0.0:
    resolution: {integrity: sha512-abc123}
    engines: {node: '>=12'}
"""


def _write(tmp_path, name, content):
    p = tmp_path / name
    p.write_text(content)
    return p


def test_parse_package_lock_v1(tmp_path):
    """v1 lockfiles use a nested dependencies tree."""
    p = _write(
        tmp_path,
        "package-lock.json",
        json.dumps(
            {
                "name": "app",
                "version": "1.0.0",
                "lockfileVersion": 1,
                "requires": True,
                "dependencies": {
                    "keyv": {
                        "version": "6.0.0",
                        "requires": {"json-buffer": "3.0.1"},
                        "dependencies": {"json-buffer": {"version": "3.0.1"}},
                    },
                    "lodash": {"version": "4.17.21"},
                },
            }
        ),
    )
    out = lockfile.parse_package_lock_v1(p)
    assert out["keyv"] == "6.0.0"
    assert out["lodash"] == "4.17.21"
    assert out["json-buffer"] == "3.0.1"  # nested deps are flattened


def test_parse_package_lock_v3(tmp_path):
    """v3 lockfiles use a flat packages map with node_modules/ prefixes."""
    p = _write(
        tmp_path,
        "package-lock.json",
        json.dumps(
            {
                "name": "app",
                "lockfileVersion": 3,
                "packages": {
                    "": {"name": "app", "dependencies": {"keyv": "^6.0.0"}},
                    "node_modules/keyv": {"version": "6.0.0"},
                    "node_modules/lodash": {"version": "4.17.21"},
                },
            }
        ),
    )
    out = lockfile.parse_package_lock_v3(p)
    assert out["keyv"] == "6.0.0"
    assert out["lodash"] == "4.17.21"


def test_parse_yarn_lock(tmp_path):
    """yarn v1 lockfiles map name -> version."""
    p = _write(tmp_path, "yarn.lock", YARN_V1)
    out = lockfile.parse_yarn_lock(p)
    assert out.get("keyv") == "6.0.0"
    assert out.get("lodash") == "4.17.21"


def test_parse_pnpm_lock(tmp_path):
    """pnpm lockfiles parse to name -> version (or degrade to {} without crash)."""
    p = _write(tmp_path, "pnpm-lock.yaml", PNPM_YAML)
    out = lockfile.parse_pnpm_lock(p)
    assert isinstance(out, dict)
    if out:  # a parser that can't handle YAML may return {}; never crash
        assert out.get("keyv") == "6.0.0"


def test_detect_lockfile_type(tmp_path):
    """Detection is driven by the file name."""
    p1 = _write(tmp_path, "package-lock.json", "{}")
    p2 = _write(tmp_path, "yarn.lock", "# yarn lockfile v1")
    p3 = _write(tmp_path, "pnpm-lock.yaml", "lockfileVersion: '6.0'")
    p4 = _write(tmp_path, "random.txt", "hi")
    assert lockfile.detect_lockfile_type(p1) == "package-lock"
    assert lockfile.detect_lockfile_type(p2) == "yarn"
    assert lockfile.detect_lockfile_type(p3) == "pnpm"
    assert lockfile.detect_lockfile_type(p4) is None


def test_parse_lockfile_dispatcher(tmp_path):
    """parse_lockfile dispatches on the detected type."""
    p = _write(
        tmp_path,
        "package-lock.json",
        json.dumps(
            {"lockfileVersion": 3, "packages": {"node_modules/keyv": {"version": "6.0.0"}}}
        ),
    )
    assert lockfile.parse_lockfile(p)["keyv"] == "6.0.0"


def test_parse_invalid_file(tmp_path):
    """Garbage content returns an empty dict instead of crashing."""
    p = _write(tmp_path, "package-lock.json", "{{{ definitely not json")
    assert lockfile.parse_lockfile(p) == {}
    assert lockfile.parse_package_lock_v1(p) == {}
    assert lockfile.parse_package_lock_v3(p) == {}
    y = _write(tmp_path, "yarn.lock", "\x00\x01\x02 not a lockfile")
    assert lockfile.parse_yarn_lock(y) == {}
